server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers**
        - id: hotel_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/hotel/**
        - id: payment_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/payments**
        - id: reservation_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/reservations/**



